<?php

namespace GroupBundle\Repository;

/**
 * commentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findcommParameter($id){
        $query = $this->getEntityManager()
            ->createQuery("
                    select Reponse from AppBundle:Reponse Reponse WHERE Reponse.idQuestion=:id
            ")
            ->setParameter('id',$id);
        return $query->getResult();
    }


}
